matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install pylint coverage python-coveralls
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - ./tests/lintAllPythonFiles.sh
        - python3 -m unittest discover tests -b
        - coverage run -m unittest discover tests -b
        - coverage report -m
      after_success:
        - coveralls
    - language: php
      php: 5.6
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - find . -type f -name *.php | xargs -n1 php -l
    - language: markdown
      addons:
        apt:
          packages:
            - aspell
            - aspell-fr
      script:
        - gem install mdl
        - cd ${TRAVIS_BUILD_DIR}
        - ./tests/tools/setCustomMDWarnings.sh
        - mdl -r $MDLWAR *.md docs/fr_FR/*.md
        - ./tests/tools/spellCheckMD.sh
